# Generated by Django 5.0.6 on 2024-05-12 17:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("surname", models.CharField(max_length=20)),
                ("phone_number", models.CharField(max_length=15)),
                (
                    "email",
                    models.CharField(
                        max_length=25,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                ("specialist", models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("surname", models.CharField(max_length=20)),
                (
                    "birth_certificate_number",
                    models.CharField(
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                regex="\\d{2}(0[1-9]|1[0-2]|5[1-9]|6[0-2])(0[1-9]|1[0-9]|2[0-9]|3[0-1])\\/?\\d{3,4}"
                            )
                        ],
                    ),
                ),
                ("phone_number", models.CharField(max_length=15)),
                ("nationality", models.CharField(max_length=10)),
                ("city", models.CharField(max_length=15)),
                ("street", models.CharField(max_length=15)),
                ("zip_code", models.IntegerField()),
                ("postal_code", models.CharField(max_length=5)),
                (
                    "email",
                    models.CharField(
                        max_length=25,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MedicationManagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("medication_item", models.CharField(max_length=50)),
                ("clinical_indication", models.CharField(max_length=50)),
                ("double_checked", models.BooleanField()),
                ("amount", models.IntegerField()),
                ("stop_date", models.DateField(default=None)),
                ("comment", models.CharField(max_length=250)),
                ("time_date", models.DateField()),
                (
                    "doctor_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cardiology.doctor",
                    ),
                ),
                (
                    "patient_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cardiology.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LaboratoryAnalyteResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("analyte_result_sequence", models.IntegerField()),
                ("analyte_name", models.CharField(max_length=25)),
                ("analyte_result", models.CharField(max_length=25)),
                ("time_date", models.DateField()),
                (
                    "doctor_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cardiology.doctor",
                    ),
                ),
                (
                    "patient_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cardiology.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ECGResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ecg_type", models.CharField(max_length=25)),
                ("arterial_heart_rate", models.IntegerField()),
                ("ventricular_heart_rate", models.IntegerField()),
                ("qt_interval_global", models.IntegerField()),
                ("qtc_interval_global", models.IntegerField()),
                ("pr_interval_global", models.IntegerField()),
                ("qrs_duration_global", models.IntegerField()),
                ("rr_interval_global", models.IntegerField()),
                ("p_axis", models.CharField(max_length=15)),
                ("qrs_axis", models.CharField(max_length=15)),
                ("t_axis", models.CharField(max_length=15)),
                ("p_amplitude", models.IntegerField()),
                ("p_duration", models.IntegerField()),
                ("q_amplitude", models.IntegerField()),
                ("q_duration", models.IntegerField()),
                ("r_amplitude", models.IntegerField()),
                ("r_duration", models.IntegerField()),
                ("s_amplitude", models.IntegerField()),
                ("s_duration", models.IntegerField()),
                ("conclusion", models.CharField(max_length=50)),
                ("ecg_diagnosis", models.CharField(max_length=50)),
                ("comment", models.CharField(max_length=250)),
                ("time_date", models.DateField()),
                (
                    "doctor_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cardiology.doctor",
                    ),
                ),
                (
                    "patient_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cardiology.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BodyMassIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bmi", models.DecimalField(decimal_places=2, max_digits=4)),
                ("clinical_interpretation", models.CharField(max_length=50)),
                ("comment", models.CharField(max_length=250)),
                ("time_date", models.DateField()),
                (
                    "doctor_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cardiology.doctor",
                    ),
                ),
                (
                    "patient_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cardiology.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BloodPressure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("systolic", models.IntegerField()),
                ("diastolic", models.IntegerField()),
                ("mean_arterial_pressure", models.IntegerField()),
                ("clinical_interpretation", models.CharField(max_length=50)),
                ("comment", models.CharField(max_length=250)),
                ("time_date", models.DateField()),
                (
                    "doctor_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cardiology.doctor",
                    ),
                ),
                (
                    "patient_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cardiology.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProblemDiagnosis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("diagnosis_name", models.CharField(max_length=50)),
                ("variant", models.CharField(max_length=50)),
                ("severity", models.IntegerField()),
                ("diagnosis_certeinity", models.IntegerField()),
                ("stop_date", models.DateField(default=None)),
                ("comment", models.CharField(max_length=250)),
                ("time_date", models.DateField()),
                (
                    "doctor_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cardiology.doctor",
                    ),
                ),
                (
                    "patient_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cardiology.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PulseHeartBeat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("presence", models.BooleanField()),
                ("rate", models.IntegerField()),
                ("irregularity", models.BooleanField()),
                ("irregular_type", models.BooleanField()),
                ("character", models.CharField(max_length=50)),
                ("clinical_description", models.CharField(max_length=50)),
                ("comment", models.CharField(max_length=250)),
                ("time_date", models.DateField()),
                (
                    "doctor_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cardiology.doctor",
                    ),
                ),
                (
                    "patient_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cardiology.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PulseOximetry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("spo2", models.DecimalField(decimal_places=1, max_digits=4)),
                ("spoc", models.DecimalField(decimal_places=1, max_digits=4)),
                ("spco", models.DecimalField(decimal_places=1, max_digits=4)),
                ("spmet", models.DecimalField(decimal_places=1, max_digits=4)),
                ("clinical_interpretation", models.CharField(max_length=50)),
                ("comment", models.CharField(max_length=250)),
                ("time_date", models.DateField()),
                (
                    "doctor_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cardiology.doctor",
                    ),
                ),
                (
                    "patient_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cardiology.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Respiration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("presence", models.BooleanField()),
                ("rate", models.IntegerField()),
                ("regularity", models.BooleanField()),
                ("clinical_interpretation", models.CharField(max_length=50)),
                ("comment", models.CharField(max_length=250)),
                ("time_date", models.DateField()),
                (
                    "doctor_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cardiology.doctor",
                    ),
                ),
                (
                    "patient_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cardiology.patient",
                    ),
                ),
            ],
        ),
    ]
