# Generated by Django 5.0.6 on 2024-05-16 12:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardiology", "0002_doctor_groups_doctor_is_active_doctor_is_staff_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="username",
            field=models.CharField(
                default=models.EmailField(
                    max_length=255,
                    unique=True,
                    validators=[django.core.validators.EmailValidator()],
                ),
                max_length=25,
                unique=True,
            ),
        ),
    ]
